server:
  port: 7002

spring:
  application:
    name: cloud-eureka-service
    #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  #互相注册
eureka:
  instance:
    hostname: eureka7002
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #填写除自身外的其他eureka服务 多个用,隔开
      defaultZone: http://eureka7001.com:7001/eureka/